//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoUploader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoUploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string main_footer_version {
            get {
                return ResourceManager.GetString("main_footer_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string main_hdr_connected {
            get {
                return ResourceManager.GetString("main_hdr_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string main_hdr_disconnected {
            get {
                return ResourceManager.GetString("main_hdr_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Image Uploader Application.
        /// </summary>
        public static string main_hdr_PhotoApplication {
            get {
                return ResourceManager.GetString("main_hdr_PhotoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Images.
        /// </summary>
        public static string main_img_deleting {
            get {
                return ResourceManager.GetString("main_img_deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Images.
        /// </summary>
        public static string main_img_Fetching {
            get {
                return ResourceManager.GetString("main_img_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Images.
        /// </summary>
        public static string main_img_uploading {
            get {
                return ResourceManager.GetString("main_img_uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string main_lbl_help {
            get {
                return ResourceManager.GetString("main_lbl_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images are uploaded succesfully..
        /// </summary>
        public static string main_msg_AllUploadSuccess {
            get {
                return ResourceManager.GetString("main_msg_AllUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is established.
        /// </summary>
        public static string main_msg_ConnectionEstablished {
            get {
                return ResourceManager.GetString("main_msg_ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is lost..
        /// </summary>
        public static string main_msg_connectionlost {
            get {
                return ResourceManager.GetString("main_msg_connectionlost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image(s) in C:\\PhotoImages folder does not exist in the camera of the connected Photo, therefore cannot be deleted..
        /// </summary>
        public static string main_msg_imagenoexist {
            get {
                return ResourceManager.GetString("main_msg_imagenoexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no images in the camera storage..
        /// </summary>
        public static string main_msg_noImage {
            get {
                return ResourceManager.GetString("main_msg_noImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is connected.
        /// </summary>
        public static string main_msg_PhotoConnected {
            get {
                return ResourceManager.GetString("main_msg_PhotoConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is not connected.
        /// </summary>
        public static string main_msg_PhotoNotConnected {
            get {
                return ResourceManager.GetString("main_msg_PhotoNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unplug and plug the camera to start the process..
        /// </summary>
        public static string main_msg_plugandunplug {
            get {
                return ResourceManager.GetString("main_msg_plugandunplug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first thing that needs paying attention is the status, Disconnected and Connected. By following the changes between these two statuses, you can understand the current situation of the process.
        ///There are 3 steps in the application: 
        ///
        ///-        Fetching the images from camera
        ///
        ///-        Uploading the fetched ones to FTP server
        ///
        ///-        Deleting the images from the camera
        ///
        ///
        ///Note that, if there is another device connected to your computer, Photo Uploader Application may have trouble on working. Please m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string main_text_help {
            get {
                return ResourceManager.GetString("main_text_help", resourceCulture);
            }
        }
    }
}
